#### input information #####
# Reference is the path to the reference to map to
reference: /oak/stanford/groups/wjg/kwells4/genomes/refdata-cellranger-GRCh38-3.0.0

# Path to the gtf file
gtf: /oak/stanford/groups/wjg/kwells4/genomes/refdata-cellranger-GRCh38-3.0.0/genes/genes.gtf

# memory to allow cell ranger to use
mem: 100

# Use this structure if all runs have identical samples

samples:
    - Tonsil1a
    - Tonsil1b
    - Tonsil2a
    - Tonsil2b
    - Tonsil3a  
    - Tonsil3b

individuals:
    Tonsil1:
        - Tonsil1a
        - Tonsil1b
    Tonsil2:
        - Tonsil2a
        - Tonsil2b
    Tonsil3:
        - Tonsil3a
        - Tonsil3b

published_samples:
    - BMMC_D1T1
    - BMMC_D1T2
    - PBMC_D4T1
    - PBMC_D4T2

subgroups:
    BCells:
        - Activated_B
        - Naive_B
        - Light_GC_B
        - Dark_GC_B
        - Plasma_B
    TCells:
        - CD4_T
        - CD8_T
    GCBcells:
        - Light_GC_B
        - Dark_GC_B
    nonLymphoid:
        - Monocyte_DC
        - Dendritic
    NonGCBcells:
        - Activated_B
        - Naive_B
        - Plasma_B
    ActiveNaiveB:
        - Activated_B
        - Naive_B